const flashcardsByChapter = {
  "Hydrocarbons": [
    { front: "General formula of alkanes?", back: "CnH2n+2" },
    { front: "Name CH≡CH", back: "Ethyne" },
    { front: "Hybridization in ethene?", back: "sp²" },
    { front: "General formula of alkanes?", back: "CnH2n+2" },
    { front: "General formula of alkenes?", back: "CnH2n" },
    { front: "General formula of alkynes?", back: "CnH2n−2" },
    { front: "Name the first member of alkynes", back: "Ethyne" },
    { front: "Hybridization in methane?", back: "sp³" },
    { front: "Hybridization in ethene?", back: "sp²" },
    { front: "Hybridization in ethyne?", back: "sp" },
    { front: "Bond angle in ethene?", back: "120°" },
    { front: "Bond angle in ethyne?", back: "180°" },
    { front: "Type of bonds in ethyne?", back: "1 sigma and 2 pi bonds" },
    { front: "Type of isomerism shown by alkenes?", back: "Geometrical (cis-trans) isomerism" },
    { front: "Which has higher boiling point: alkane or alkene?", back: "Alkene (due to polarity)" },
    { front: "Free radical substitution occurs in?", back: "Alkanes" },
    { front: "Mechanism of halogenation of alkanes?", back: "Free radical mechanism" },
    { front: "Which step in halogenation is chain-initiating?", back: "Homolytic cleavage (Initiation)" },
    { front: "What is the major product in chlorination of propane?", back: "2-Chloropropane" },
    { front: "Order of reactivity: F₂ > Cl₂ > Br₂ > I₂?", "back": "Correct (based on bond dissociation)" },
    { front: "What is Markovnikov’s rule?", back: "H⁺ attaches to the carbon with more H atoms" },
    { front: "Exception to Markovnikov’s rule?", back: "In presence of peroxide (anti-Markovnikov)" },
    { front: "Name the product: CH₃CH=CH₂ + HBr?", back: "2-Bromopropane (Markovnikov product)" },
    { front: "Name the product with peroxide: CH₃CH=CH₂ + HBr?", back: "1-Bromopropane" },
    { front: "Test to detect unsaturation?", "back": "Bromine water or Baeyer’s test" },
    { front: "Which hydrocarbons decolorize Br₂ water?", back: "Alkenes and alkynes" },
    { front: "What happens in Baeyer’s test?", back: "Purple KMnO₄ turns colorless" },
    { front: "Major product in oxymercuration of alkenes?", back: "Markovnikov alcohol" },
    { front: "Name reaction: Alkene + B₂H₆ → Alcohol?", back: "Hydroboration-oxidation (anti-Markovnikov)" },
    { front: "Oxidation product of terminal alkynes with KMnO₄?", back: "Carboxylic acids" },
    { front: "What is ozonolysis used for?", back: "To locate position of double bonds" },
    { front: "Ozonolysis of CH₂=CH₂ gives?", back: "Formaldehyde (HCHO)" },
    { front: "What is the IUPAC name of isobutene?", back: "2-methylpropene" },
    { front: "Alkyne + H₂ in Lindlar’s catalyst gives?", back: "Cis-alkene" },
    { front: "Alkyne + Na/NH₃ gives?", back: "Trans-alkene" },
    { front: "Which hybrid orbitals form the triple bond?", back: "sp (sigma) and 2 unhybridized p (pi)" },
    { front: "Which is more acidic: Ethyne or ethene?", back: "Ethyne (sp > sp²)" },
    { front: "Order of acidity: Ethyne > Ethene > Ethane. Why?", back: "Higher s-character = more acidic" },
    { front: "What are conjugated dienes?", back: "Dienes with alternating double and single bonds" },
    { front: "Example of conjugated diene?", back: "1,3-Butadiene" },
    { fromt: "What is hyperconjugation?", back: "Delocalization of σ electrons from C–H to adjacent π system" },
    { front: "Order of stability of alkenes?", back: "Tetra > tri > di > mono-substituted" },
    { front: "Zaitsev’s rule is used in?", back: "Dehydration or dehydrohalogenation to get major alkene" },
    { front: "What is the Zaitsev product?", back: "More substituted (stable) alkene" },
    { front: "Alkyne → Ketone via hydration. Reagent?", back: "H₂O, H₂SO₄, HgSO₄" },
    { front: "Which reaction forms vinyl halide?", back: "Electrophilic addition of HX to alkyne" },
    { front: "What is a vinyl group?", back: "–CH=CH₂ group attached to a parent chain" },
    { front: "Why are alkynes less reactive in addition?", back: "π-electrons held tightly (sp)" },
    { front: "Test to distinguish alkyne from alkene?", back: "Ammoniacal AgNO₃ (tollens reagent) — alkynes form ppt" },
    { front: "Which hydrocarbon reacts with AgNO₃?", back: "Terminal alkynes" },
    { front: "What are aromatic hydrocarbons?", back: "Cyclic compounds with delocalized π electrons (Hückel’s rule)" },
    { front: "Hybridization of carbon in benzene?", back: "sp²" },
    { front: "Bond order in benzene?", back: "1.5 (due to resonance)" }
  ],,
  "Alcohols, Phenols & Ethers": [
    { front: "Functional group of alcohols?", back: "–OH" },
    { front: "Phenol example: C6H5OH is …?", back: "Phenol" },
    { front: "Ether general formula?", back: "R–O–R" },
    { front: "General formula of haloalkanes?", back: "CnH2n+1X" },
    { front: "General formula of dihaloalkanes?", back: "CnH2nX2" },
    { front: "What is a primary alkyl halide?", back: "Halogen attached to a primary carbon" },
    { front: "What is a tertiary alkyl halide?", back: "Halogen attached to a tertiary carbon" },
    { front: "IUPAC name of CH3CH2Cl?", back: "Chloroethane" },
    { front: "Which bond is weaker: C–Cl or C–I?", back: "C–I (due to lower bond dissociation energy)" },
    { front: "Which is more reactive in SN1: R–Cl or R–I?", back: "R–I (better leaving group)" },
    { front: "Which mechanism: Tertiary alkyl halide + aqueous KOH?", back: "SN1" },
    { front: "Which mechanism: Methyl halide + NaOH (aq)?", back: "SN2" },
    { front: "Which mechanism: 2-bromopropane + NaOH?", back: "SN1/SN2 (depends on solvent)" },
    { front: "What is the order of reactivity in SN1?", back: "3° > 2° > 1° > methyl" },
    { front: "What is the order of reactivity in SN2?", back: "Methyl > 1° > 2° > 3°" },
    { front: "What is inversion of configuration?", back: "Flipping of chiral center in SN2 (Walden inversion)" },
    { front: "Which step is rate-determining in SN1?", back: "Formation of carbocation (slow step)" },
    { front: "SN1 reactions are favored by which solvent?", back: "Polar protic (e.g., H₂O, alcohol)" },
    { front: "SN2 reactions are favored by which solvent?", back: "Polar aprotic (e.g., acetone, DMSO)" },
    { front: "In SN2, how many steps occur?", back: "One (concerted mechanism)" },
    { front: "Which halide is least reactive in SN2?", back: "Tertiary halide (due to steric hindrance)" },
    { front: "What is a racemic mixture?", back: "Equal amounts of enantiomers (formed in SN1)" },
    { front: "Which base favors E2 over SN2?", back: "Strong bulky base (e.g., tert-butoxide)" },
    { front: "What determines E1 vs SN1?", back: "Temperature and base strength" },
    { front: "Dehydrohalogenation follows which mechanism?", back: "E2 or E1 depending on substrate" },
    { front: "Major product of E2 reaction?", back: "More substituted alkene (Zaitsev product)" },
    { front: "What is a vicinal dihalide?", back: "Two halogens on adjacent carbons" },
    { front: "What is a geminal dihalide?", back: "Two halogens on the same carbon" },
    { front: "Which reagent converts alcohol to alkyl halide?", back: "SOCl₂, PCl₅, HBr etc." },
    { front: "Product of CH₃CH₂OH + SOCl₂?", back: "CH₃CH₂Cl (ethyl chloride)" },
    { front: "Which halide is formed with NaBr + H₂SO₄?", back: "Alkyl bromide" },
    { front: "Why aryl halides are less reactive?", back: "Due to resonance and partial double bond character" },
    { front: "Can aryl halides undergo SN1 or SN2?", back: "No, due to instability of intermediate and steric hindrance" },
    { front: "What is the effect of –NO₂ on aryl halide reactivity?", back: "Increases reactivity via –M and –I effects" },
    { front: "Nucleophile attacks which position in aryl halides?", back: "Ortho and para (activated by –NO₂)" },
    { front: "What is Finkelstein reaction?", back: "Halide exchange using NaI in acetone" },
    { front: "What is Swarts reaction?", back: "R–Cl or R–Br → R–F using AgF or SbF₃" },
    { front: "Product of C₂H₅Cl + NaI (acetone)?", back: "C₂H₅I (ethyl iodide)" },
    { front: "Which halogen acts as best leaving group?", back: "I⁻" },
    { front: "Best nucleophile among halide ions?", back: "I⁻ (largest size, most polarizable)" },
    { front: "What is the role of acetone in Finkelstein?", back: "Dissolves NaCl (drives equilibrium forward)" },
    { front: "Grignard reagent is prepared from?", back: "Alkyl halide + Mg in dry ether" },
    { front: "Grignard reagent reacts with water to form?", back: "Alkane" },
    { front: "How is DDT prepared?", back: "Chlorobenzene + chloral in presence of H₂SO₄" },
    { front: "Why is DDT banned?", back: "Non-biodegradable and toxic" },
    { front: "Which reagent distinguishes 1°, 2°, 3° halides?", back: "Alcoholic AgNO₃ (white ppt forms fastest with 3°)" },
    { front: "Which halogen is least reactive in nucleophilic substitution?", back: "Fluorine (strongest C–F bond)" },
    { front: "Reaction of aryl halide with CuCN gives?", back: "Aryl cyanide (Sandmeyer reaction)" },
    { front: "Reagent for reduction of alkyl halide to alkane?", back: "Zn/HCl or LiAlH₄" },
    { front: "Which reaction forms alkene from haloalkane?", back: "Dehydrohalogenation (E2)" },
    { front: "Chlorobenzene + NaOH (300°C, 200 atm) →?", back: "Phenol (Dow’s process)" },
    { front: "Why is benzylic halide reactive?", back: "Forms stable benzyl carbocation" },
    { front: "What is Wurtz reaction?", back: "2R–X + 2Na → R–R + 2NaX (in dry ether)" },
    { front: "Which mechanism is concerted and stereospecific?", back: "SN2" },
    { front: "What is Saytzeff’s rule?", back: "Major alkene = more substituted (stable) alkene" },
    { front: "Example of aryl halide?", back: "Chlorobenzene" },
    { front: "Why does chlorobenzene resist hydrolysis?", back: "Resonance and double bond character in C–Cl" },
    { front: "Which halide reacts fastest in hydrolysis?", back: "Tertiary alkyl halide" },
    { front: "Hybridization of C in C–X bond of haloalkanes?", back: "sp³" },
    { front: "What is the role of Zn in haloalkane reduction?", back: "Provides electrons to reduce R–X to R–H" },
    { front: "How many products in SN1 on chiral carbon?", back: "Two (racemic mixture)" }
  
  "Aldehydes, Ketones & Carboxylic Acids": [
    { front: "Functional group of aldehydes?", back: "–CHO" },
    { front: "Functional group of ketones?", back: ">C=O" },
    { front: "Name CH3COOH", back: "Ethanoic acid" },
    { front: "General formula of aldehydes?", back: "R–CHO" },
    { front: "General formula of ketones?", back: "R–CO–R′" },
    { front: "General formula of carboxylic acids?", back: "R–COOH" },
    { front: "Functional group of aldehydes?", back: "–CHO" },
    { front: "Functional group of ketones?", back: "–CO–" },
    { front: "Functional group of carboxylic acids?", back: "–COOH" },
    { front: "IUPAC name of HCHO?", back: "Methanal" },
    { front: "IUPAC name of CH3COCH3?", back: "Propanone" },
    { front: "IUPAC name of CH3COOH?", back: "Ethanoic acid" },
    { front: "Which test is used to distinguish aldehyde from ketone?", back: "Tollens’ test or Fehling’s test" },
    { front: "Tollens’ reagent contains?", back: "[Ag(NH3)2]+ (ammoniacal silver nitrate)" },
    { front: "Positive Tollens’ test gives?", back: "Silver mirror" },
    { front: "Fehling’s solution gives positive test with?", back: "Aldehydes (not ketones)" },
    { front: "Which reagent oxidizes aldehyde to carboxylic acid?", back: "KMnO4, K2Cr2O7, or Tollens’ reagent" },
    { front: "Can ketones be oxidized easily?", back: "No, only under strong conditions" },
    { front: "Aldehyde + H2/Ni gives?", back: "Primary alcohol" },
    { front: "Ketone + H2/Ni gives?", back: "Secondary alcohol" },
    { front: "Reaction: Aldehyde + alcohol (acid catalyzed)?", back: "Hemiacetal/Acetal formation" },
    { front: "What is nucleophile in nucleophilic addition to carbonyl?", back: "Species like H⁻, CN⁻, R–MgX" },
    { front: "Reagent to convert aldehyde/ketone to cyanohydrin?", back: "HCN" },
    { front: "Reagent for oxime formation?", back: "NH2OH (hydroxylamine)" },
    { front: "Reagent for hydrazone formation?", back: "NH2NH2 (hydrazine)" },
    { front: "Reagent for semicarbazone formation?", back: "NH2NHCONH2 (semicarbazide)" },
    { front: "Which reagent reduces aldehydes/ketones to alcohols?", back: "NaBH4 or LiAlH4" },
    { front: "Reagent for Clemmensen reduction?", back: "Zn/Hg + HCl" },
    { front: "Reagent for Wolff–Kishner reduction?", back: "NH2NH2 + KOH, heat" },
    { front: "Reagent for Rosenmund reduction?", back: "H2, Pd/BaSO4 (Lindlar's catalyst)" },
    { front: "What is Cannizzaro reaction?", back: "Base-induced disproportionation of aldehydes without α-H" },
    { front: "Product of Cannizzaro reaction?", back: "Alcohol and carboxylic acid" },
    { front: "Example of aldehyde that gives Cannizzaro reaction?", back: "HCHO (formaldehyde)" }, 
    { front: "What is aldol condensation?", back: "Aldehydes/ketones with α-H form β-hydroxy compound" },
    { front: "What is product of aldol condensation on heating?", back: "α,β-unsaturated carbonyl compound" },
    { front: "Which compound gives aldol condensation?", back: "Aldehyde/ketone with α-hydrogen" },
    { front: "Which acid gives vinegar smell?", back: "Acetic acid (ethanoic acid)" },
    { front: "Carboxylic acid + alcohol (acidic condition)?", back: "Ester + water (esterification)" },
    { front: "Reagent for ester hydrolysis?", back: "Dil. acid or base (acid/base hydrolysis)" },
    { front: "Acidic hydrolysis of ester gives?", back: "Carboxylic acid and alcohol" },
    { front: "Basic hydrolysis of ester gives?", back: "Carboxylate salt and alcohol" },
    { front: "What is decarboxylation?", back: "Loss of CO2 from carboxylic acid" },
    { front: "Reagent for decarboxylation?", back: "Soda lime (NaOH + CaO)" },
    { front: "Which acid gives brisk effervescence with NaHCO3?", back: "Carboxylic acid (due to CO2 release)" },
    { front: "Which acid is used in food preservatives?", back: "Benzoic acid" },
    { front: "What is the effect of –NO2 on acidity of carboxylic acid?", back: "Increases acidity (–I effect)" },
    { front: "What is the effect of –CH3 on acidity of carboxylic acid?", back: "Decreases acidity (+I effect)" },
    { front: "Which is more acidic: formic acid or acetic acid?", back: "Formic acid" },
    { front: "What is acyl group?", back: "R–CO– group" },
    { front: "What are acid chlorides?", back: "Derivatives of carboxylic acids with –COCl group" },
    { front: "What is Hell–Volhard–Zelinsky reaction?", back: "α-halogenation of carboxylic acid using PCl3 + Br2" },
    { front: "Why α-hydrogen in aldehyde/ketone is acidic?", back: "Due to resonance stabilization of enolate ion" },
    { front: "What are enolates?", back: "Conjugate base of carbonyl compounds formed by deprotonation at α-position" }
  ],
  "Haloalkanes & Haloarenes": [
    { front: "Functional group of haloalkanes?", back: "–X (halogen)" },
    { front: "Reactivity order: RI, RBr, RCl, RF?", back: "RI > RBr > RCl > RF" },
    { front: "What is chloromethane?", back: "CH3Cl" },
  { front: "General formula of aldehydes?", back: "R–CHO" },
  { front: "General formula of ketones?", back: "R–CO–R'" },
  { front: "General formula of carboxylic acids?", back: "R–COOH" },
  { front: "Hybridization of carbon in carbonyl group?", back: "sp²" },
  { front: "Bond angle in carbonyl compound?", back: "Around 120°" },
  { front: "Why are aldehydes more reactive than ketones?", back: "Less steric hindrance and more positive carbon" },
  { front: "Common test to distinguish aldehyde from ketone?", back: "Tollen's and Fehling's tests" },
  { front: "Tollen’s reagent contains?", back: "Ammoniacal silver nitrate (AgNO₃ + NH₃)" },
  { front: "Positive Tollen’s test gives?", back: "Silver mirror (aldehydes only)" },
  { front: "Fehling’s test forms?", back: "Red precipitate of Cu₂O (aldehydes only)" },
  { front: "Why ketones don't give Tollen's/Fehling’s?", back: "They can’t be oxidized easily" },
  { front: "What is nucleophile in nucleophilic addition to carbonyl?", back: "CN⁻, H⁻, R⁻, NH₂OH, etc." },
  { front: "Aldehyde + HCN gives?", back: "Cyanohydrin" },
  { front: "Aldehyde + NH₂OH gives?", back: "Oxime" },
  { front: "Aldehyde + 2,4-DNP gives?", back: "Hydrazone (used as test)" },
  { front: "Reagent for reduction of aldehyde to alcohol?", back: "NaBH₄ or LiAlH₄" },
  { front: "Aldehyde + alcohol (acid catalyzed) gives?", back: "Hemiacetal, then acetal" },
  { front: "Ketone + alcohol gives?", back: "Hemiketal, then ketal" },
  { front: "What is aldol condensation?", back: "Aldehyde/ketone (with α-H) forms β-hydroxy carbonyl" },
  { front: "Aldol product on heating gives?", back: "α,β-unsaturated aldehyde or ketone" },
  { front: "What is Cannizzaro reaction?", back: "Disproportionation of non-enolizable aldehydes" },
  { front: "Cannizzaro gives which products?", back: "Alcohol + salt of acid" },
  { front: "Which aldehyde shows Cannizzaro?", back: "Formaldehyde, benzaldehyde" },
  { front: "Clemmensen reduction uses?", back: "Zn(Hg) + HCl (acidic medium)" },
  { front: "Wolff–Kishner reduction uses?", back: "Hydrazine + KOH + heat (basic medium)" },
  { front: "Oxidation of aldehyde gives?", back: "Carboxylic acid" },
  { front: "Oxidation of ketone gives?", back: "No reaction (hard to oxidize)" },
  { front: "Which is more acidic: formic acid or acetic acid?", back: "Formic acid (no +I group)" },
  { front: "Acidity order: formic > acetic > propanoic. Why?", back: "Increasing +I effect reduces acidity" },
  { front: "Why carboxylic acids are acidic?", back: "Resonance-stabilized carboxylate ion" },
  { front: "Effect of –NO₂ on acidity of acids?", back: "Increases acidity (–M and –I effect)" },
  { front: "Decarboxylation reagent?", back: "NaOH and heat" },
  { front: "Product of R–COOH + SOCl₂?", back: "Acyl chloride (R–COCl)" },
  { front: "Product: Carboxylic acid + alcohol + H⁺?", back: "Ester (Fischer esterification)" },
  { front: "Hydrolysis of ester gives?", back: "Alcohol + Carboxylic acid" },
  { front: "What is HVZ reaction?", back: "Halogenation at α-position of carboxylic acids" },
  { front: "Which hydrogen in aldehydes is acidic?", back: "α-Hydrogen (forms enolate)" },
  { front: "Which reaction forms α-halogenated acid?", back: "Hell-Volhard-Zelinsky (HVZ) reaction" },
  { front: "Which gives iodoform test: acetaldehyde or benzaldehyde?", back: "Acetaldehyde" },
  { front: "Iodoform test: yellow ppt indicates?", back: "Presence of CH₃–CO group" },
  { front: "Aldehyde with no α-H shows?", back: "Cannizzaro reaction" },
  { front: "Reagent to convert acid → alcohol?", back: "LiAlH₄" },
  { front: "Reagent to convert aldehyde → alkane?", back: "Clemmensen or Wolff-Kishner" },
  { front: "Why benzoic acid is more acidic than acetic acid?", back: "Phenyl ring withdraws electrons" },
  { front: "Which carbonyl is most reactive?", back: "Formaldehyde" },
  { front: "Why ketones are less reactive?", back: "Two electron-donating groups reduce δ⁺ on carbon" },
  { front: "Acidity of phenol vs benzoic acid?", back: "Benzoic acid > phenol" },
  { front: "What is Tischenko reaction?", back: "Aldehydes → esters (Al(OR)₃ catalyst)" },
  { front: "Tollens test: Ag⁺ is reduced to?", back: "Metallic silver (Ag)" },
  { front: "What is the enol form?", back: "OH attached to C=C" },
  { front: "Enolization occurs in?", back: "Aldehydes/ketones with α-H" },
  { front: "Functional group in aldehyde?", back: "–CHO" },
  { front: "Functional group in ketone?", back: "–CO–" },
  { front: "Ketone with α-H + Br₂ gives?", back: "α-Bromoketone (halogenation)" },
  { front: "Aromatic aldehyde + conc. NaOH gives?", back: "Cannizzaro reaction products" },
  { front: "Reactivity order: formaldehyde > acetaldehyde > ketone?", back: "Correct" },
  { front: "Which acid is used in aspirin synthesis?", back: "Salicylic acid" },
  { front: "Benzaldehyde + NaOH gives?", back: "Cannizzaro (benzyl alcohol + benzoate)" },
  { front: "Ester + NH₃ gives?", back: "Amide" },
  { front: "Which compound gives two 2,4-DNP products?", back: "Compounds with two carbonyl groups" },
  { front: "Why carboxylic acids have high boiling points?", back: "Dimerization via H-bonding" },
  { front: "Which carbonyl compound is used in making paracetamol?", back: "p-Aminophenol → acetanilide derivative" },
  { front: "Formic acid is oxidized to?", back: "CO₂ and H₂O" },
  { front: "Ethanal + H₂/Pd gives?", back: "Ethanol" }
  ],
  "Amines": [
    { front: "Functional group of amines?", back: "–NH2, –NHR, –NR2" },
    { front: "Primary amine example: CH3NH2 is …", back: "Methylamine" },
    { front: "Test for primary amine?", back: "Carbylamine test" },
    { front: "General formula of amines?", back: "R–NH₂ (primary), R₂NH (secondary), R₃N (tertiary)" },
    { front: "Classification of amines?", back: "Primary, Secondary, Tertiary based on number of alkyl groups attached to N" },
    { front: "Hybridization of nitrogen in amines?", back: "sp³" },
    { front: "Why are amines basic?", back: "Lone pair on nitrogen can accept a proton" },
    { front: "Order of basicity: aromatic amines vs aliphatic amines?", back: "Aliphatic amines > aromatic amines" },
    { front: "Why are aromatic amines less basic?", back: "Lone pair delocalized in aromatic ring (less available)" },
    { front: "Which amine is most basic: methylamine, aniline, ammonia?", back: "Methylamine" },
    { front: "Effect of electron donating groups on amine basicity?", back: "Increase basicity" },
    { front: "Effect of electron withdrawing groups on amine basicity?", back: "Decrease basicity" },
    { front: "Preparation of primary amines from alkyl halides?", back: "R–X + NH₃ → R–NH₂" },
    { front: "Problem in direct amine preparation from alkyl halide?", back: "Multiple alkylations lead to mixture of amines" },
    { front: "Gabriel phthalimide synthesis gives?", back: "Primary amines selectively" },
    { front: "Reduction of nitriles gives?", back: "Primary amines" },
    { front: "Reduction of nitrobenzene gives?", back: "Aniline" },
    { front: "Reagents for reduction of nitrobenzene?", back: "Sn/HCl or Fe/HCl" },
    { front: "Hofmann bromamide reaction converts?", back: "Primary amide to primary amine (one carbon less)" },
    { front: "What is Hofmann elimination?", back: "Quaternary ammonium salt heated → alkene + tertiary amine" },
    { front: "Reaction of amines with nitrous acid?", back: "Primary aromatic amines form diazonium salts" },
    { front: "Diazonium salt is stable at?", back: "0–5°C" },
    { front: "What happens to primary aliphatic amines with nitrous acid?", back: "Form unstable diazonium salts → N₂ gas evolves" },
    { front: "What is Sandmeyer reaction?", back: "Diazonium salt + CuX → aryl halide" },
    { front: "Reagent to prepare aryl halides from aryl diazonium salts?", back: "CuCl, CuBr, or CuCN" },
    { front: "What is azo coupling?", back: "Electrophilic substitution of diazonium salt with phenol or aromatic amines" },
    { front: "Why is trimethylamine more basic than ammonia?", back: "Electron donation from methyl groups increases lone pair density" },
    { front: "Why is triethylamine less basic than trimethylamine?", back: "Steric hindrance reduces availability of lone pair" },
    { front: "What is Hoffmann rearrangement?", back: "Amide to amine with one less carbon" },
    { front: "Which amines form salts with acids?", back: "All amines (primary, secondary, tertiary)" },
    { front: "Amines + HCl gives?", back: "Ammonium chloride salts" },
    { front: "Which amines are insoluble in water?", back: "Higher amines (long chain)" },
    { front: "Order of boiling points: amines, alkanes, alcohols?", back: "Alcohols > amines > alkanes" },
    { front: "Reason for lower boiling point of tertiary amines?", back: "No hydrogen bonding between molecules" },
    { front: "Why primary amines have higher boiling points than tertiary?", back: "Intermolecular hydrogen bonding" },
    { front: "Identification test for primary aromatic amines?", back: "Diazotization test (form diazonium salt)" },
    { front: "What is methyl orange?", back: "pH indicator derived from azo compounds" },
    { front: "Reaction of amines with acyl chlorides?", back: "Forms amides" },
    { front: "Why is aniline less reactive towards electrophilic substitution?", back: "Lone pair delocalizes into ring reducing electron density" },
    { front: "Effect of –NO₂ on aniline's basicity?", back: "Decreases basicity" },
    { front: "Effect of –CH₃ on aniline's basicity?", back: "Increases basicity" },
    { front: "Preparation of diazonium salt?", back: "Aniline + NaNO₂ + HCl (0–5°C)" },
    { front: "Which amines undergo Hofmann elimination?", back: "Quaternary ammonium salts" },
    { front: "How are quaternary ammonium salts prepared?", back: "Tertiary amine + alkyl halide" },
    { front: "What is Gabriel synthesis?", back: "Preparation of primary amines using phthalimide" },
    { front: "What is Hinsberg test?", back: "Distinguishes primary, secondary, tertiary amines" },
    { front: "Result of Hinsberg test for 1° amine?", back: "Forms soluble sulfonamide" },
    { front: "Result of Hinsberg test for 2° amine?", back: "Forms insoluble sulfonamide" },
    { front: "Result of Hinsberg test for 3° amine?", back: "No reaction" },
    { front: "Aromatic amines + nitrous acid at room temperature?", back: "Form diazonium salt" },
    { front: "What is the reagent for reductive amination?", back: "NaBH₃CN" },
    { front: "Primary amine + nitrous acid at 0°C?", back: "Forms diazonium salt (aromatic) or unstable intermediates (aliphatic)" },
    { front: "Why are aromatic diazonium salts important?", back: "Precursors for azo dyes and other substitutions" },
    { front: "Which amines react with nitrous acid to form alcohols?", back: "Primary aliphatic amines" },
    { front: "Why are tertiary amines not diazotized?", back: "No N–H bond to form diazonium salt" },
    { front: "What is the role of sodium nitrite in diazotization?", back: "Generates nitrous acid in situ" },
    { front: "Amines + nitrous acid generate?", back: "Diazonium salts or N₂ gas" },
    { front: "Effect of electron withdrawing groups on amine basicity?", back: "Decrease basicity" },
    { front: "Effect of electron donating groups on amine basicity?", back: "Increase basicity" },
    { front: "Aromatic amine to azo dye involves?", back: "Coupling reaction with phenol or aromatic amine" },
    { front: "What is azo dye?", back: "Colored compound containing –N=N– group" },
    { front: "What is the shape of amine molecule?", back: "Trigonal pyramidal" }
  ],
  "Biomolecules": [
    { front: "Glucose is a …", back: "Monosaccharide" },
    { front: "Basic unit of proteins?", back: "Amino acids" },
    { front: "Lipid example?", back: "Triglyceride" },
    { front: "General formula of monosaccharides?", back: "(CH₂O)n" },
    { front: "Example of a triose sugar?", back: "Glyceraldehyde" },
    { front: "Difference between aldose and ketose?", back: "Aldose has aldehyde group; ketose has ketone group" },
    { front: "What is an epimer?", back: "Stereoisomers differing in configuration at one carbon" },
    { front: "What is mutarotation?", back: "Change in optical rotation due to equilibrium between α and β anomers" },
    { front: "What is glycosidic bond?", back: "Bond between two sugar molecules via oxygen" },
    { front: "Difference between α and β glucose?", back: "Position of –OH on C1: down (α), up (β)" },
    { front: "Disaccharides examples?", back: "Sucrose, lactose, maltose" },
    { front: "Which bond links glucose units in starch?", back: "α-1,4 and α-1,6 glycosidic bonds" },
    { front: "Which polysaccharide is storage form in plants?", back: "Starch" },
    { front: "Storage polysaccharide in animals?", back: "Glycogen" },
    { front: "Structural polysaccharide in plants?", back: "Cellulose" },
    { front: "Why can humans not digest cellulose?", back: "Lack of β-glucosidase enzyme" },
    { front: "What are essential amino acids?", back: "Amino acids not synthesized by the body" },
    { front: "Structure of amino acid?", back: "Central carbon with amino, carboxyl, hydrogen, and R group" },
    { front: "What determines protein structure?", back: "Sequence of amino acids (primary structure)" },
    { front: "Types of protein structures?", back: "Primary, secondary, tertiary, quaternary" },
    { front: "What is peptide bond?", back: "Amide bond between amino acids" },
    { front: "What is denaturation of protein?", back: "Loss of structure and function due to external factors" },
    { front: "Types of enzymes?", back: "Oxidoreductases, transferases, hydrolases, lyases, isomerases, ligases" },
    { front: "What is enzyme specificity?", back: "Ability to act on specific substrates" },
    { front: "What is cofactors in enzymes?", back: "Non-protein molecules assisting enzyme function" },
    { front: "Difference between coenzyme and prosthetic group?", back: "Coenzyme loosely bound, prosthetic group tightly bound" },
    { front: "What is Michaelis constant (Km)?", back: "Substrate concentration at half-max velocity" },
    { front: "Effect of competitive inhibitor on Km and Vmax?", back: "Km increases, Vmax unchanged" },
    { front: "Effect of non-competitive inhibitor on Km and Vmax?", back: "Km unchanged, Vmax decreases" },
    { front: "What are lipids?", back: "Biomolecules soluble in nonpolar solvents" },
    { front: "Types of lipids?", back: "Simple (fats, oils), compound (phospholipids), derived (steroids)" },
    { front: "Structure of triglycerides?", back: "Glycerol + 3 fatty acids" },
    { front: "Difference between saturated and unsaturated fatty acids?", back: "Saturated have no double bonds; unsaturated have one or more" },
    { front: "What is saponification?", back: "Hydrolysis of fats to soap and glycerol" },
    { front: "What are nucleic acids?", back: "DNA and RNA, polymers of nucleotides" },
    { front: "Components of a nucleotide?", back: "Nitrogenous base, pentose sugar, phosphate group" },
    { front: "Difference between DNA and RNA sugar?", back: "DNA has deoxyribose; RNA has ribose" },
    { front: "Base pairing in DNA?", back: "A–T (2 H bonds), G–C (3 H bonds)" },
    { front: "What is central dogma of molecular biology?", back: "DNA → RNA → Protein" },
    { front: "Types of RNA?", back: "mRNA, tRNA, rRNA" },
    { front: "What is vitamins?", back: "Essential organic compounds required in small amounts" },
    { front: "Water-soluble vitamins?", back: "B-complex and C" },
    { front: "Fat-soluble vitamins?", back: "A, D, E, K" },
    { front: "Function of vitamin C?", back: "Antioxidant, collagen synthesis" },
    { front: "Function of vitamin D?", back: "Calcium absorption and bone health" },
    { front: "What is enzyme inhibitor?", back: "Molecule reducing enzyme activity" },
    { front: "What is allosteric enzyme?", back: "Enzyme regulated by effector binding at site other than active site" },
    { front: "What is lock and key model?", back: "Enzyme specificity due to complementary shapes" },
    { front: "What is induced fit model?", back: "Enzyme changes shape to fit substrate" },
    { front: "What is primary structure of protein?", back: "Sequence of amino acids" },
    { front: "Secondary structure of protein?", back: "α-helix and β-pleated sheets" },
    { front: "What stabilizes tertiary structure?", back: "Hydrogen bonds, disulfide bridges, ionic interactions" },
    { front: "What is enzyme turnover number?", back: "Number of substrate molecules converted per enzyme per second" },
    { front: "What are essential fatty acids?", back: "Fatty acids that must be obtained from diet" },
    { front: "What is difference between DNA and RNA in structure?", back: "DNA is double-stranded; RNA is single-stranded" },
    { front: "What is glycation?", back: "Non-enzymatic bonding of sugar to proteins or lipids" },
    { front: "What is metabolic role of carbohydrates?", back: "Energy source and storage" },
    { front: "What is role of lipids in cell membranes?", back: "Structural component forming lipid bilayer" },
    { front: "What is allosteric regulation?", back: "Modulation of enzyme activity through binding of effectors" },
    { front: "What is coenzyme NAD+ role?", back: "Electron carrier in oxidation reactions" },
    { front: "What is difference between purines and pyrimidines?", back: "Purines have two rings (A, G); pyrimidines have one ring (C, T, U)" },
    { front: "What is ribozyme?", back: "RNA molecule with catalytic activity" },
    { front: "What is role of ATP?", back: "Primary energy currency of the cell" },
    { front: "What is enzyme specificity?", back: "Ability of enzyme to select substrate" }
  ],
  "Polymers": [
    { front: "Natural polymer: Cellulose or PVC?", back: "Cellulose" },
    { front: "Monomer of polythene?", back: "Ethene" },
    { front: "Synthetic polymer: Nylon is a …", back: "Polyamide" },
    { front: "What is a polymer?", back: "Large molecule made of repeating units called monomers" },
    { front: "Types of polymers?", back: "Natural and synthetic" },
    { front: "Examples of natural polymers?", back: "Cellulose, starch, proteins, natural rubber" },
    { front: "Examples of synthetic polymers?", back: "Polythene, nylon, bakelite, PVC" },
    { front: "Difference between addition and condensation polymerization?", back: "Addition: monomers add without loss; Condensation: monomers join with loss of small molecules" },
    { front: "Monomer of polythene?", back: "Ethene" },
    { front: "Monomer of nylon-6,6?", back: "Hexamethylene diamine and adipic acid" },
    { front: "What is a copolymer?", back: "Polymer made from two or more different monomers" },
    { front: "Example of copolymer?", back: "Buna-S (styrene and butadiene)" },
    { front: "What is vulcanization?", back: "Treatment of rubber with sulfur to improve elasticity" },
    { front: "What is thermoplastic?", back: "Polymer softens on heating and hardens on cooling" },
    { front: "What is thermosetting polymer?", back: "Polymer that does not soften on heating" },
    { front: "Monomer of PVC?", back: "Vinyl chloride" },
    { front: "What is degree of polymerization?", back: "Number of monomer units in a polymer chain" },
    { front: "What is cross-linking in polymers?", back: "Chemical bonds linking polymer chains" },
    { front: "What is an elastomer?", back: "Polymer with elastic properties" },
    { front: "Example of elastomer?", back: "Natural rubber" },
    { front: "What is addition polymerization?", back: "Polymerization without loss of atoms" },
    { front: "What is condensation polymerization?", back: "Polymerization with elimination of small molecules" },
    { front: "Difference between LDPE and HDPE?", back: "LDPE is branched and has low density; HDPE is linear with high density" }
  ],
  "Chemistry in Everyday Life": [
    { front: "Vitamin C is …", back: "Ascorbic acid" },
    { front: "Common painkiller: Paracetamol is …", back: "Analgesic" },
    { front: "Antibiotic example?", back: "Penicillin" },
    { front: "What is the role of chemistry in everyday life?", back: "Chemistry explains the composition and reactions of materials around us" },
    { front: "Examples of chemicals in medicines?", back: "Antibiotics, analgesics, antiseptics" },
    { front: "What is an analgesic?", back: "A drug that relieves pain without causing loss of consciousness" },
    { front: "Name a common antibiotic used to treat bacterial infections.", back: "Penicillin" },
    { front: "What is the function of an antiseptic?", back: "To kill or inhibit the growth of microorganisms on living tissues" },
    { front: "What are disinfectants?", back: "Chemicals used to destroy microorganisms on non-living objects" },
    { front: "Give an example of a commonly used disinfectant.", back: "Bleach (sodium hypochlorite)" },
    { front: "What are antioxidants and their role in everyday life?", back: "Substances that prevent oxidation and delay spoilage of food" },
    { front: "Name a natural antioxidant.", back: "Vitamin C (ascorbic acid)" },
    { front: "What is the importance of preservatives in food?", back: "To increase shelf life by preventing microbial growth" },
    { front: "Give an example of a food preservative.", back: "Sodium benzoate" },
    { front: "What are detergents and how do they work?", back: "Cleaning agents that remove grease and dirt by emulsifying oils" }, 
    { front: "Difference between soap and detergent?", back: "Soap is biodegradable and made from natural fats; detergents are synthetic and work in hard water" },
    { front: "What is hard water and why is it a problem for soaps?", back: "Water with dissolved calcium and magnesium salts that reduce soap’s effectiveness" },
    { front: "What is the role of Vitamin D in the human body?", back: "Helps in calcium absorption and bone health" },
    { front: "How is aspirin chemically classified?", back: "As a non-steroidal anti-inflammatory drug (NSAID)" },
    { front: "What is the chemical formula of aspirin?", back: "C9H8O4" },
    { front: "What is the difference between synthetic and natural drugs?", back: "Synthetic drugs are chemically manufactured; natural drugs are extracted from plants or animals" },
    { front: "Name a synthetic drug commonly used as a painkiller.", back: "Paracetamol" },
    { front: "What are the side effects of antibiotics misuse?", back: "Antibiotic resistance and reduced effectiveness" },
    { front: "What is an antacid and give an example?", back: "A substance that neutralizes stomach acid; e.g., magnesium hydroxide" },
    { front: "What is the role of chemistry in agriculture?", back: "Development of fertilizers, pesticides, and herbicides to increase crop yield" },
    { front: "What are fertilizers?", back: "Substances that supply essential nutrients to plants" },
    { front: "Name two important nutrients in fertilizers.", back: "Nitrogen and phosphorus" },
    { front: "What are pesticides?", back: "Chemicals used to kill pests harmful to crops" },
    { front: "Give an example of an organic pesticide.", back: "DDT (Dichlorodiphenyltrichloroethane)" },
    { front: "What is the environmental concern with DDT?", back: "It is persistent and causes bioaccumulation in the food chain" },
    { front: "What is the role of polymers in everyday life?", back: "Used in making plastics, packaging, and clothing materials" },
    { front: "Name a natural polymer.", back: "Cellulose" },
    { front: "Name a synthetic polymer.", back: "Polyethylene" },
    { front: "What is the chemical basis of soap’s cleaning action?", back: "Soap molecules have hydrophilic heads and hydrophobic tails that trap dirt in micelles" },
    { front: "What is a pharmaceutical drug?", back: "A chemical substance used to diagnose, treat, or prevent disease" },
    { front: "What is an analgesic’s mode of action?", back: "Blocks the production of pain-causing chemicals (prostaglandins)" },
    { front: "Name a household product that contains acetic acid.", back: "Vinegar" },
    { front: "How does baking soda help in everyday life?", back: "Used as a leavening agent and to neutralize odors" },
    { front: "What is the chemical formula of baking soda?", back: "NaHCO3" },
    { front: "What is the importance of water chemistry in daily life?", back: "Determines water quality for drinking, cooking, and cleaning" },
    { front: "What is a buffer solution?", back: "A solution that resists changes in pH upon addition of acid or base" },
    { front: "Why is chlorine added to drinking water?", back: "To kill harmful microorganisms and disinfect water" },
    { front: "What is a common example of a vitamin essential for human health?", back: "Vitamin A" },
    { front: "What is the role of chemistry in cosmetics?", back: "Formulation of skincare, haircare, and makeup products" },
    { front: "What is the chemical composition of common table salt?", back: "Sodium chloride (NaCl)" },
    { front: "What is the difference between a physical and chemical change?", back: "Physical change alters state or appearance without changing composition; chemical change alters composition" },
    { front: "How are soaps made chemically?", back: "By saponification of fats/oils with a strong base like NaOH" },
    { front: "What is the role of ethanol in everyday life?", back: "Used as a solvent, disinfectant, and in alcoholic beverages" },
    { front: "What are synthetic fibers and examples?", back: "Man-made fibers like nylon and polyester used in textiles" },
    { front: "How does chemistry help in food flavoring?", back: "By synthesizing artificial flavors and preservatives" },
    { front: "What is the chemical basis of antiperspirants?", back: "Aluminum salts that block sweat glands" },
    { front: "Why is organic chemistry important in everyday life?", back: "It helps in understanding molecules in drugs, fuels, plastics, and food" }
  ],
  "Practical Organic Chemistry / Tests": [
    { front: "Iodoform test +ive for …", back: "Ethanol/acetone" },
    { front: "Silver mirror test = …", back: "Aldehydes" },
    { front: "Bromine water test decolorises for …", back: "Alkenes, phenols, aldehydes" },
    { front: "What is the purpose of recrystallization in organic practicals?", back: "To purify solid organic compounds by dissolving impurities in a solvent" },
    { front: "Name a common solvent used in recrystallization.", back: "Ethanol or water" },
    { front: "What does melting point determination indicate about an organic compound?", back: "Purity and identity of the compound" },
    { front: "Why does an impure compound have a lower and broader melting point range?", back: "Impurities disrupt the crystal lattice, lowering melting point and broadening the range" },
    { front: "What is Thin Layer Chromatography (TLC) used for?", back: "To separate and identify components in a mixture" },
    { front: "What is the stationary phase in TLC?", back: "Silica gel or alumina coated on a plate" },
    { front: "What is the mobile phase in TLC?", back: "A suitable solvent or solvent mixture" },
    { front: "What does the Rf value in TLC represent?", back: "Ratio of distance traveled by compound to distance traveled by solvent front" },
    { front: "How do you calculate Rf value?", back: "Rf = (Distance traveled by substance) / (Distance traveled by solvent front)" },
    { front: "Name a test to identify aldehydes.", back: "Tollens' test (silver mirror test)" }, 
    { front: "What is observed in a positive Tollens' test?", back: "Formation of a silver mirror on the inner surface of the test tube" },
    { front: "Name a test to distinguish between aldehydes and ketones.", back: "Fehling's test" },
    { front: "What happens in a positive Fehling's test?", back: "Formation of a brick-red precipitate" },
    { front: "Which test is used to detect phenols?", back: "Ferric chloride test" },
    { front: "What is the color change in a positive ferric chloride test?", back: "Formation of violet or purple complex" },
    { front: "How can you confirm the presence of a carboxylic acid?", back: "Effervescence with sodium bicarbonate (CO2 gas evolved)" },
    { front: "What is the purpose of using sodium bicarbonate in carboxylic acid detection?", back: "It reacts with acid to release CO2 gas indicating acidity" },
    { front: "Which test is used to identify alkenes?", back: "Bromine water test" },
    { front: "What indicates a positive bromine water test for alkenes?", back: "Discoloration of bromine water from orange to colorless" },
    { front: "How do you test for the presence of primary, secondary, and tertiary alcohols?", back: "Lucas test" },
    { front: "What observation confirms a tertiary alcohol in Lucas test?", back: "Immediate formation of cloudy solution or separate layer" },
    { front: "What is the principle of sodium fusion test?", back: "To detect elements like nitrogen, sulfur, and halogens in organic compounds" },
    { front: "How is nitrogen detected in sodium fusion test?", back: "By adding ferrous sulfate and acid to give Prussian blue precipitate" },
    { front: "Name a reagent used for the bromination of phenol.", back: "Bromine water" },
    { front: "What is the observation in bromination of phenol?", back: "Formation of a white precipitate of 2,4,6-tribromophenol" }, 
    { front: "What is the purpose of distillation in organic practicals?", back: "To separate liquids based on boiling points" },
    { front: "Differentiate between simple and fractional distillation.", back: "Simple separates liquids with large boiling point differences; fractional is used for close boiling points" },
    { front: "What is the use of the iodine test?", back: "To detect starch presence" },
    { front: "What is the observation in a positive iodine test?", back: "Formation of blue-black color" },
    { front: "Name the test used to detect unsaturation in organic compounds.", back: "Baeyer’s test using potassium permanganate (KMnO4)" },
    { front: "What does a positive Baeyer’s test show?", back: "Disappearance of purple color and formation of brown precipitate" },
    { front: "How do you test for the presence of nitro compounds?", back: "Brown ring test (for nitrate ion)" },
    { front: "What is the role of sodium metal in sodium fusion test?", back: "To convert organic compounds into ionic forms for element detection" },
    { front: "How to prepare a derivative of an organic compound?", back: "Reacting the compound with suitable reagent to form a solid derivative for purification and characterization" },
    { front: "What is the purpose of preparing organic derivatives?", back: "To confirm the identity of organic compounds by melting point comparison" },
    { front: "Name a derivative prepared for carboxylic acids.", back: "Acid chloride or acid anhydride" },
    { front: "Name a common test for detecting halogens in organic compounds.", back: "Beilstein test" },
    { front: "What is observed in a positive Beilstein test?", back: "Green flame on copper wire due to halogen" },
    { front: "What does the iodoform test detect?", back: "Presence of methyl ketones or ethanol" },
    { front: "What observation indicates a positive iodoform test?", back: "Formation of a yellow precipitate of iodoform (CHI3)" },
    { front: "How is the solubility test helpful in organic practical?", back: "Helps to classify compounds as polar or non-polar" },
    { front: "Name a method to separate immiscible liquids.", back: "Separating funnel" },
    { front: "What is saponification in organic practical?", back: "Hydrolysis of ester to form alcohol and soap (salt of carboxylic acid)" },
    { front: "What reagent is used in saponification?", back: "Aqueous sodium hydroxide" },
    { front: "What is the purpose of performing a neutralization test?", back: "To detect acidic or basic nature of an organic compound" },
    { front: "How to test for aromaticity in an organic compound?", back: "Conducting electrophilic substitution reactions like nitration or bromination" },
    { front: "Name a common electrophilic substitution reaction used in organic practicals.", back: "Nitration of benzene" },
    { front: "What precautions should be taken during organic distillation?", back: "Avoid overheating, use boiling chips to prevent bumping" }, 
    { front: "How is IR spectroscopy helpful in organic practical?", back: "Identifies functional groups by characteristic absorption bands" },
    { front: "What does a positive iodoform test indicate about the structure?", back: "Presence of CH3-CO- or CH3-CH(OH)- group" },
    { front: "Why is sodium bicarbonate test not positive for phenols?", back: "Phenols are weak acids and do not react with sodium bicarbonate to release CO2" }
  ]
};

let currentChapter = "Hydrocarbons";
let currentSet = flashcardsByChapter[currentChapter];
let currentCard = 0;

function loadChapter(chapter) {
  currentChapter = chapter;
  currentSet = flashcardsByChapter[chapter];
  currentCard = 0;
  showCard(0);
}

function showCard(index) {
  const front = document.getElementById("cardFront");
  const back = document.getElementById("cardBack");
  front.innerText = currentSet[index].front;
  back.innerText = currentSet[index].back;
  document.getElementById("flashcard").classList.remove("flip");
  document.getElementById("cardCounter").innerText = `${index + 1} / ${currentSet.length}`;
}

function flipCard() {
  document.getElementById("flashcard").classList.toggle("flip");
}

function nextCard() {
  currentCard = (currentCard+1) % currentSet.length;
  showCard(currentCard);
}

function prevCard() {
  currentCard = (currentCard-1+currentSet.length) % currentSet.length;
  showCard(currentCard);
}

window.onload = () => {
  loadChapter(currentChapter);
};
